import Link from 'next/link';
import { KIND_LABELS, hrefFor, search, type SearchHit, type SearchKind } from '@/lib/search';

/**
 * What order the groups come in — and, more usefully, a guarantee that every
 * kind is in it.
 *
 * This was an array, and an array of a union type is happy to be missing a
 * member: adding `box_item` to the search made the query return documents and
 * this page drop them on the floor, with the result count including hits that
 * were never rendered. A `Record` cannot be incomplete, so the next kind added
 * is a compile error here rather than a group that silently never appears.
 */
const KIND_ORDER: Record<SearchKind, number> = {
  project: 0,
  action: 1,
  list_item: 2,
  inbox: 3,
  box_item: 4,
  attachment: 5,
};

const KINDS = (Object.keys(KIND_ORDER) as SearchKind[]).sort(
  (a, b) => KIND_ORDER[a] - KIND_ORDER[b],
);

export default async function SearchPage(props: PageProps<'/search'>) {
  const searchParams = await props.searchParams;
  const term = typeof searchParams.q === 'string' ? searchParams.q : '';
  const hits = await search(term);

  const grouped = KINDS.map((kind) => ({
    kind,
    hits: hits.filter((h) => h.kind === kind),
  })).filter((g) => g.hits.length > 0);

  return (
    <div className="min-w-0 flex-1 overflow-y-auto bg-paper">
      <div className="max-w-[46rem] px-8 py-7">
        <h1 className="text-xl font-semibold text-grey-900">
          {term ? <>Results for “{term}”</> : 'Search'}
        </h1>

        {!term ? (
          <p className="mt-2 max-w-prose text-[13px] leading-relaxed text-grey-600">
            Searches project and action titles and their notes, list items, raw
            inbox captures, everything filed in a box, and what your files
            actually say. Quoted phrases, <code>-exclusions</code> and{' '}
            <code>OR</code> all work.
          </p>
        ) : hits.length === 0 ? (
          <p className="mt-3 text-[13px] text-grey-500">
            Nothing matched. Full-text search matches whole words, so try a
            shorter or more distinctive term.
          </p>
        ) : (
          <>
            <p className="mt-1 text-[12px] text-grey-500">
              {hits.length} result{hits.length === 1 ? '' : 's'}, best first
            </p>

            <div className="mt-5 space-y-6">
              {grouped.map((group) => (
                <section key={group.kind}>
                  <h2 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-grey-500">
                    {KIND_LABELS[group.kind]}
                    <span className="ml-1.5 tabular-nums text-grey-400">
                      {group.hits.length}
                    </span>
                  </h2>
                  <div className="overflow-hidden rounded-sm border border-grey-200">
                    {group.hits.map((hit) => (
                      <Result key={`${hit.kind}-${hit.id}`} hit={hit} />
                    ))}
                  </div>
                </section>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function Result({ hit }: { hit: SearchHit }) {
  return (
    <Link
      href={hrefFor(hit)}
      className="block border-b border-grey-150 px-3 py-2.5 last:border-b-0 hover:bg-grey-100"
    >
      <div className="flex items-baseline justify-between gap-2">
        <span className="truncate text-[13px] text-grey-800">{hit.title}</span>
        {hit.context ? (
          <span className="shrink-0 text-[11px] text-grey-500">{hit.context}</span>
        ) : null}
      </div>

      {/* ts_headline returns the matched terms wrapped in <mark>. The input is
          our own column text and the markup is generated by Postgres, not by
          the user, so rendering it is safe — but keep it to <mark> only. */}
      {hit.snippet ? (
        <p
          className="mt-1 text-[12px] leading-relaxed text-grey-600 [&_mark]:bg-selected-bg [&_mark]:font-medium [&_mark]:text-selected"
          dangerouslySetInnerHTML={{ __html: sanitiseHeadline(hit.snippet) }}
        />
      ) : null}
    </Link>
  );
}

/**
 * ts_headline escapes nothing, so a note containing "<script>" would come back
 * verbatim. Strip every tag except the <mark> pair we asked Postgres for.
 */
function sanitiseHeadline(html: string): string {
  return html
    .replace(/<(?!\/?mark>)[^>]*>/g, '')
    .replace(/&(?!(amp|lt|gt|quot|#\d+);)/g, '&amp;');
}
